customhost = "assignment.cegsftmiit0a.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "bait3273"
customdb = "employee"
custombucket = "yowkeanyung-assignnment"
customregion = "us-east-1"
